<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Title>ZeroPinyin</Title>
        <Authors>神麤詭末</Authors>
        <Description>一个高性能、零内存分配的即时中文拼音匹配引擎</Description>
        <Version>1.0.3</Version>
        <PackageProjectUrl>https://github.com/scgm0/ZeroPinyin</PackageProjectUrl>
        <RepositoryUrl>https://github.com/scgm0/ZeroPinyin.git</RepositoryUrl>
        <PackageTags>Pinyin;Chinese;Search;NFA;ZeroPinyin;Matcher</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="../Resource/pinyin.txt" />
    </ItemGroup>
    
    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="/" />
        <None Include="../LICENSE" Pack="true" PackagePath="/" />
    </ItemGroup>
</Project>
